# Generated by Django 4.2 on 2023-04-29 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='digital.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quantity', models.IntegerField(default=0, verbose_name='В наличии')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('size', models.IntegerField(default=2, verbose_name='Размер памяти')),
                ('color', models.CharField(default='White', max_length=30, verbose_name='Цвет')),
                ('body', models.CharField(max_length=255, verbose_name='Корпус')),
                ('battery', models.CharField(max_length=255, verbose_name='Аккумулятор')),
                ('technology', models.CharField(max_length=255, verbose_name='Технология')),
                ('display', models.IntegerField(default=0, verbose_name='Размер дисплея')),
                ('back_camera', models.CharField(max_length=255, verbose_name='Камера основная')),
                ('front_camera', models.CharField(max_length=255, verbose_name='Камера фронтальная')),
                ('operation_system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('guarantee', models.IntegerField(default=0, verbose_name='Гарантия')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digital.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='digital.product')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея товаров',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.product', verbose_name='Избранный товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
            },
        ),
    ]
