# Generated by Django 4.2 on 2023-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Размер дисплея'),
        ),
    ]
