# Generated by Django 4.2 on 2023-05-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_alter_product_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
    ]
