# Generated by Django 4.2 on 2023-05-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_productdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operation_system',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technology',
        ),
    ]
