# Generated by Django 4.2 on 2023-05-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_remove_product_back_camera_remove_product_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='parameter',
            field=models.TextField(verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='parameter_info',
            field=models.TextField(verbose_name='Описание параметра'),
        ),
    ]
