# Generated by Django 4.2 on 2023-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_alter_productdescription_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='parameter',
            field=models.CharField(max_length=255, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='parameter_info',
            field=models.CharField(max_length=500, verbose_name='Описание параметра'),
        ),
    ]
