# Generated by Django 4.2 on 2023-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0014_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='White', max_length=30, verbose_name='Цвет'),
        ),
    ]
