# Generated by Django 4.2 on 2023-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0016_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='from_price',
            field=models.IntegerField(default=0, verbose_name='От какой стоимости'),
        ),
    ]
