# Generated by Django 4.2 on 2023-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0019_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
