# Generated by Django 4.2 on 2023-05-05 14:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0020_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
