# Generated by Django 4.2.1 on 2023-05-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0024_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='publisher',
        ),
    ]
