# Generated by Django 4.2.1 on 2023-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0026_city_customer_order_shippingaddress_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='color_name',
            field=models.CharField(blank=True, default='Белый', max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
