# Generated by Django 4.2.1 on 2023-05-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0028_gallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
