# Generated by Django 4.2.1 on 2023-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0029_remove_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(blank=True, default=1, verbose_name='Пямать'),
            preserve_default=False,
        ),
    ]
