# Generated by Django 4.2.1 on 2023-05-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0032_alter_product_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование Бренда'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital.modelproduct', verbose_name='Модель'),
        ),
    ]
