# Generated by Django 4.2.1 on 2023-05-17 05:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0033_modelproduct_alter_brand_title_product_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет'),
        ),
    ]
