# Generated by Django 4.2.1 on 2023-05-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0035_remove_gallery_color_remove_gallery_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='digital.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_product', to='digital.category', verbose_name='Категория'),
        ),
    ]
