# Generated by Django 4.2.1 on 2023-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0039_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255, verbose_name='Название города'),
        ),
    ]
