# Generated by Django 4.2.1 on 2023-05-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0040_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
