# Generated by Django 4.2.1 on 2023-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0043_orderproduct_total_price_alter_orderproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
