# Generated by Django 4.2.1 on 2023-05-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0049_alter_saveorder_order_delete_savecheckorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveorder',
            options={'verbose_name': 'История товаров заказа', 'verbose_name_plural': 'Истории товаров заказов'},
        ),
        migrations.RenameField(
            model_name='saveorder',
            old_name='addet_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='saveorder',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='saveorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saveorder',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='saveorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='saveorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.customer'),
        ),
        migrations.CreateModel(
            name='SaveOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('product_price', models.FloatField(verbose_name='Цена')),
                ('final_price', models.FloatField(verbose_name='Цена то')),
                ('addet_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.saveorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.orderproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История товаров заказа',
                'verbose_name_plural': 'Истории товаров заказов',
            },
        ),
    ]
