# Generated by Django 4.2.1 on 2023-05-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0050_alter_saveorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveorder',
            options={'verbose_name': 'История  заказа', 'verbose_name_plural': 'Истории  заказов'},
        ),
        migrations.RemoveField(
            model_name='saveorder',
            name='order',
        ),
    ]
