# Generated by Django 4.2.1 on 2023-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0051_alter_saveorder_options_remove_saveorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproducts',
            name='product',
            field=models.TextField(default=1, max_length=255, verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
