# Generated by Django 4.2.1 on 2023-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0052_alter_saveorderproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproducts',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Продукт'),
        ),
    ]
