# Generated by Django 4.2.1 on 2023-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0054_alter_saveorderproducts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorder',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Сумма чека'),
        ),
    ]
