# Generated by Django 4.2.1 on 2023-05-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0055_saveorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderproducts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='save_order_products/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='saveorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.customer', verbose_name='Покупатель'),
        ),
    ]
