# Generated by Django 4.2.1 on 2023-05-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0057_alter_saveorderproducts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproducts',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digital.saveorder'),
        ),
    ]
