# Generated by Django 4.2.1 on 2023-05-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0060_alter_saveorderproducts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproducts',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
