# Generated by Django 4.2.1 on 2023-05-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0061_alter_saveorderproducts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorderproducts',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
    ]
